name: release-drafter

on:
  push:
    branches:
      - 'main'
  pull_request_target:
    # Only following types are handled by the action, but one can default to all as well
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update-draft-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v5.24.0
        id: release_drafter
        with:
          config-name: release-drafter-config.yml
          disable-autolabeler: false
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        id: version
        run: echo "${{ steps.release_drafter.outputs.resolved_version }}" > VERSION
      - name: Calculate code
        id: code
        run: |
          IFS='.' read -ra VER <<< "$(cat VERSION)"
          MAJOR=$((VER[0] * 1000000000))
          MINOR=$((VER[1] * 1000000))
          PATCH=$((VER[2] * 1000))
          CODE=$((MAJOR + MINOR + PATCH))
          echo "version=$(cat VERSION)" > gradle/version.properties
          echo "code=$CODE" >> gradle/version.properties
          echo "name=v$(cat VERSION)" >> gradle/version.properties

      - name: Show version
        run: cat gradle/version.properties

      - name: Push auto generated version file
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: "chore: update version.properties"
          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: chore/update-version-meta-data
          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff --amend --no-edit'
          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: 'gradle/version.properties'
          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: .
          # Optional commit user and author settings
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
          # Optional. Create given branch name in local and remote repository.
          create_branch: true
          push_options: '--force'
          skip_fetch: true
