name: release-draft-trigger

on:
  release:
    types:
      - created
      - edited
    published:
      false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Triggered on release draft
        run: |
          echo "Release draft created or updated!"
          echo "Draft Tag: ${{ github.event.release.tag_name }}"
