name: test-runner

on: [push, pull_request]

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: python test-sum.py
  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r .github/scripts/requirements.txt
      - name: Run unit tests
        run: python .github/scripts/test_release_updater.py
