name: Bump version and generate version.properties
on:
  push:
    tags:
      - '*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version
        id: version
        run: echo "name=version::$(echo $GITHUB_REF | sed 's|.*/||')" >> $GITHUB_OUTPUT

      - name: Calculate code
        id: code
        run: |
          IFS='.' read -ra VER <<< "${{ steps.version.outputs.version }}"
          MAJOR=$((VER[0] * 1000000000))
          MINOR=$((VER[1] * 10000))
          PATCH=${VER[2]}
          CODE=$((MAJOR + MINOR + PATCH))
          echo "version=${{ steps.version.outputs.version }}" > gradle/version.properties
          echo "code=$CODE" >> gradle/version.properties
          echo "name=v${{ steps.version.outputs.version }}" >> gradle/version.properties

      - name: Show version
        run: cat gradle/version.properties

      - name: Check if version.properties has changed
        id: version-changed
        run: echo ::set-output name=changed::$(if git diff --quiet gradle/version.properties; then echo "false"; else echo "true"; fi)

      - name: Commit version.properties
        run: |
          git config --local user.email "github-action@github.com"
          git config --local user.name "GitHub Action"
          git add gradle/version.properties
          git commit -m "Update version.properties to ${{ steps.version.outputs.version }}"
        
      - name: Push changes
        if: steps.version-changed.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
